#!/bin/bash -u
# Test typical usage for the evry program
# shellcheck disable=SC2181

rm_if_exists() {
	[[ -e "$1" ]] && rm "$1"
}

cargo build || exit $?
evry='./target/debug/evry'

export EVRY_DEBUG=1

TAG_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/evry/data/evrytest"

rm_if_exists "$TAG_FILE"

# test non-existent file
"$evry" 5 seconds -evrytest
(($? == 0)) && echo '.' || echo "FAIL, exit code ${?} from non existing tag file"

# test existing file within duration
"$evry" 5 seconds -evrytest
(($? == 0)) && echo "FAIL: call within duration caused zero exit code" || echo '.'

# sleep to elapse duration
sleep 5

# test existing file when duration has elapsed
"$evry" 5 seconds -evrytest
(($? == 0)) && echo '.' || echo "FAIL: after duration has elapsed, failed with non zero exit code"

sleep 5
# test the typical usage, with a rollback it it fails
# in this case, the command fails
rm_if_exists "$TAG_FILE"
